{
  "project_id": 809346,
  "preserve_hierarchy": true,
  "files": [
    {
      "source": "/build/locale/404.pot",
      "dest": "404.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/404.po"
    },
    {
      "source": "/build/locale/codelists.pot",
      "dest": "codelists.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/codelists.po"
    },
    {
      "source": "/build/locale/governance/deprecation.pot",
      "dest": "governance/deprecation.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/governance/deprecation.po"
    },
    {
      "source": "/build/locale/governance/index.pot",
      "dest": "governance/index.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/governance/index.po"
    },
    {
      "source": "/build/locale/guidance/build/change_history.pot",
      "dest": "guidance/build/change_history.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/build/change_history.po"
    },
    {
      "source": "/build/locale/guidance/build/data_collection_tools.pot",
      "dest": "guidance/build/data_collection_tools.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/build/data_collection_tools.po"
    },
    {
      "source": "/build/locale/guidance/build/easy_releases.pot",
      "dest": "guidance/build/easy_releases.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/build/easy_releases.po"
    },
    {
      "source": "/build/locale/guidance/build/hosting.pot",
      "dest": "guidance/build/hosting.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/build/hosting.po"
    },
    {
      "source": "/build/locale/guidance/build/merging.pot",
      "dest": "guidance/build/merging.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/build/merging.po"
    },
    {
      "source": "/build/locale/guidance/build/serialization.pot",
      "dest": "guidance/build/serialization.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/build/serialization.po"
    },
    {
      "source": "/build/locale/guidance/build/system_architectures.pot",
      "dest": "guidance/build/system_architectures.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/build/system_architectures.po"
    },
    {
      "source": "/build/locale/guidance/build.pot",
      "dest": "guidance/build.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/build.po"
    },
    {
      "source": "/build/locale/guidance/design/user_needs.pot",
      "dest": "guidance/design/user_needs.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/design/user_needs.po"
    },
    {
      "source": "/build/locale/guidance/design.pot",
      "dest": "guidance/design.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/design.po"
    },
    {
      "source": "/build/locale/guidance/index.pot",
      "dest": "guidance/index.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/index.po"
    },
    {
      "source": "/build/locale/guidance/map/amendments.pot",
      "dest": "guidance/map/amendments.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/amendments.po"
    },
    {
      "source": "/build/locale/guidance/map/awards_contracts.pot",
      "dest": "guidance/map/awards_contracts.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/awards_contracts.po"
    },
    {
      "source": "/build/locale/guidance/map/beneficial_ownership.pot",
      "dest": "guidance/map/beneficial_ownership.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/beneficial_ownership.po"
    },
    {
      "source": "/build/locale/guidance/map/buyers_suppliers.pot",
      "dest": "guidance/map/buyers_suppliers.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/buyers_suppliers.po"
    },
    {
      "source": "/build/locale/guidance/map/electronic_catalogues.pot",
      "dest": "guidance/map/electronic_catalogues.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/electronic_catalogues.po"
    },
    {
      "source": "/build/locale/guidance/map/extensions.pot",
      "dest": "guidance/map/extensions.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/extensions.po"
    },
    {
      "source": "/build/locale/guidance/map/framework_agreements.pot",
      "dest": "guidance/map/framework_agreements.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/framework_agreements.po"
    },
    {
      "source": "/build/locale/guidance/map/linked_standards.pot",
      "dest": "guidance/map/linked_standards.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/linked_standards.po"
    },
    {
      "source": "/build/locale/guidance/map/localization.pot",
      "dest": "guidance/map/localization.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/localization.po"
    },
    {
      "source": "/build/locale/guidance/map/milestones.pot",
      "dest": "guidance/map/milestones.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/milestones.po"
    },
    {
      "source": "/build/locale/guidance/map/organization_classifications.pot",
      "dest": "guidance/map/organization_classifications.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/organization_classifications.po"
    },
    {
      "source": "/build/locale/guidance/map/organization_identifiers.pot",
      "dest": "guidance/map/organization_identifiers.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/organization_identifiers.po"
    },
    {
      "source": "/build/locale/guidance/map/organization_personal_identifiers.pot",
      "dest": "guidance/map/organization_personal_identifiers.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/organization_personal_identifiers.po"
    },
    {
      "source": "/build/locale/guidance/map/organization_reference.pot",
      "dest": "guidance/map/organization_reference.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/organization_reference.po"
    },
    {
      "source": "/build/locale/guidance/map/organizational_units.pot",
      "dest": "guidance/map/organizational_units.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/organizational_units.po"
    },
    {
      "source": "/build/locale/guidance/map/pre-qualification.pot",
      "dest": "guidance/map/pre-qualification.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/pre-qualification.po"
    },
    {
      "source": "/build/locale/guidance/map/unsuccessful_processes.pot",
      "dest": "guidance/map/unsuccessful_processes.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map/unsuccessful_processes.po"
    },
    {
      "source": "/build/locale/guidance/map.pot",
      "dest": "guidance/map.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/map.po"
    },
    {
      "source": "/build/locale/guidance/publish/quality.pot",
      "dest": "guidance/publish/quality.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/publish/quality.po"
    },
    {
      "source": "/build/locale/guidance/publish.pot",
      "dest": "guidance/publish.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/guidance/publish.po"
    },
    {
      "source": "/build/locale/history/changelog.pot",
      "dest": "history/changelog.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/history/changelog.po"
    },
    {
      "source": "/build/locale/history/history_and_development.pot",
      "dest": "history/history_and_development.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/history/history_and_development.po"
    },
    {
      "source": "/build/locale/history/index.pot",
      "dest": "history/index.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/history/index.po"
    },
    {
      "source": "/build/locale/index.pot",
      "dest": "index.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/index.po"
    },
    {
      "source": "/build/locale/primer/how.pot",
      "dest": "primer/how.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/primer/how.po"
    },
    {
      "source": "/build/locale/primer/index.pot",
      "dest": "primer/index.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/primer/index.po"
    },
    {
      "source": "/build/locale/primer/next.pot",
      "dest": "primer/next.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/primer/next.po"
    },
    {
      "source": "/build/locale/primer/releases_and_records.pot",
      "dest": "primer/releases_and_records.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/primer/releases_and_records.po"
    },
    {
      "source": "/build/locale/primer/what.pot",
      "dest": "primer/what.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/primer/what.po"
    },
    {
      "source": "/build/locale/schema/codelists.pot",
      "dest": "schema/codelists.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/codelists.po"
    },
    {
      "source": "/build/locale/schema/conformance_and_extensions.pot",
      "dest": "schema/conformance_and_extensions.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/conformance_and_extensions.po"
    },
    {
      "source": "/build/locale/schema/identifiers.pot",
      "dest": "schema/identifiers.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/identifiers.po"
    },
    {
      "source": "/build/locale/schema/index.pot",
      "dest": "schema/index.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/index.po"
    },
    {
      "source": "/build/locale/schema/merging.pot",
      "dest": "schema/merging.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/merging.po"
    },
    {
      "source": "/build/locale/schema/record_package.pot",
      "dest": "schema/record_package.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/record_package.po"
    },
    {
      "source": "/build/locale/schema/records_reference.pot",
      "dest": "schema/records_reference.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/records_reference.po"
    },
    {
      "source": "/build/locale/schema/reference.pot",
      "dest": "schema/reference.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/reference.po"
    },
    {
      "source": "/build/locale/schema/release.pot",
      "dest": "schema/release.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/release.po"
    },
    {
      "source": "/build/locale/schema/release_package.pot",
      "dest": "schema/release_package.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema/release_package.po"
    },
    {
      "source": "/build/locale/schema.pot",
      "dest": "schema.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/schema.po"
    },
    {
      "source": "/build/locale/sphinx.pot",
      "dest": "sphinx.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/sphinx.po"
    },
    {
      "source": "/build/locale/support/index.pot",
      "dest": "support/index.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/support/index.po"
    },
    {
      "source": "/build/locale/theme.pot",
      "dest": "theme.pot",
      "translation": "/docs/locale/%two_letters_code%/LC_MESSAGES/theme.po"
    }
  ]
}