name: CI
on: [push, pull_request]
jobs:
  build:
    uses: open-contracting/.github/.github/workflows/ci-profile.yml@main
    secrets:
      private-key: ${{ secrets.PRIVATE_KEY }}
      elasticsearch-password: ${{ secrets.ELASTICSEARCH_PASSWORD }}
    with:
      path-prefix: ''
      version: '1.1'
      production-refs: '["refs/heads/1.0", "refs/heads/1.1"]'
      # Linkcheck is slow for development.
      linkcheck: false
      # "ResourceWarning: unclosed file <_io.BufferedWriter name='/dev/null'>"
      pytest-options: -W ignore::ResourceWarning
