name: Spell-check
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/spellcheck.yml@main
    with:
      ignore: fo,sme,zar
      skip: docson,locale,examples,country.csv,currency.csv,language.csv,mediaType.csv
